$('.owl-carousel').owlCarousel({
    ltr:true,
    loop:true,
    margin:5,
    autoplay:true,
    dots:false,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:6
        }
    }
})